server:
  port: 8080

spring:
  application:
    name: async

logging:
  level:
    root: INFO
    com.async.engine: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
